### ISSUE TITLE
Question: is this the API for Ingenico PDQ Move 3500?

### ISSUE THREAD

**Issue by rebbieboi** [Worldline-Global-Collect/connect-sdk-php#1]
When i opened their (ingenico website) contact page it had a link to worldline. So I'm confused if you're just one entity considering you just rebranded and if this is the API we can use for PDQ Move 3500.

Thank you

**Comment by georgiosWorldline** [comment]
These SDKs are meant for the eCommerce solution called Worldline Global Collect and the API called Connect.

Ingenico as a company was acquired by Worldline in 2020, but Worldline sold part of its (legacy) terminal business and the brand Ingenico.

I think what you are looking for, can be found here: https://developer.ingenico.com/

Hope that helps 😃

**Comment by rebbieboi** [comment]
aye, I already reached out to their support team they're not that quick to reply though. :D
